### ISSUE TITLE
Assembly files are required

### ISSUE THREAD

**Issue by Msey** [Msey/battle-city-multiplayer#6]
**Need to include .csproj and .sln files to the current repository for work**

I can't generate it, and that method with toggling script editor doesn't help anymore

**Comment by Vitek1425** [comment]
https://github.com/Msey/battle-city-multiplayer/blob/8578c802b6525d79bfe0431ce52117e63523a627/.gitignore#L34
https://github.com/Msey/battle-city-multiplayer/blob/8578c802b6525d79bfe0431ce52117e63523a627/.gitignore#L36
.csproj and .sln files are auto generated
